In [1]:
from selenium import webdriver
from selenium.webdriver.support.ui import Select
from bs4 import BeautifulSoup
import pandas as pd
browser = webdriver.Chrome(executable_path=
r'C:\Users\hugohu\Dropbox\ShareWith_Hugo\CourseFile\chromedriver_win32\chromedriver')
browser.get("http://taqm.epa.gov.tw/taqm/tw/MonthlyAverage.aspx")

In [2]:
selectSite = Select(browser.find_element_by_id("ctl05_ddlSite"))
selectSite.select_by_value('58')
selectYear = Select(browser.find_element_by_id("ctl05_ddlYear"))
selectYear.select_by_value('2018')
browser.find_element_by_id('ctl05_btnQuery').click()

In [3]:
html_source = browser.page_source
soup = BeautifulSoup(html_source, 'html.parser')
table = soup.find('table', class_='TABLE_G')
browser.quit()

In [4]:
dataList = []
c = 0
tList = []
for i in table.find('tbody').find_all('td'):
    tList.append(i.text.replace('\n','').replace('\xa0',''))
    c += 1
    while c==38:
        dataList.append(tList)
        tList = []
        c = 0

In [5]:
result = {}
for i in dataList:
    title = '{}({})'.format(i[0], i[1])
    c = 0
    tList = []
    rList = {}
    for data in i[2:]:
        tList.append(data)
        c += 1
        while c%3 == 0:
            rList[tList[0]] = tList[1]
            c = 0
            tList = []
            break
    result[title] = rList
result

{'SO2(ppb)': {'2018/01': '6',
  '2018/02': '4.30',
  '2018/03': '6.30',
  '2018/04': '7.10',
  '2018/05': '9.40',
  '2018/06': '7.90',
  '2018/07': '6',
  '2018/08': '7.60',
  '2018/09': '7.10',
  '2018/10': '6.70',
  '2018/11': '6.40',
  '2018/12': '5.60'},
 'CO(ppm)': {'2018/01': '0.62',
  '2018/02': '0.59',
  '2018/03': '0.45',
  '2018/04': '0.34',
  '2018/05': '0.23',
  '2018/06': '0.33',
  '2018/07': '0.27',
  '2018/08': '0.37',
  '2018/09': '0.35',
  '2018/10': '0.47',
  '2018/11': '0.52',
  '2018/12': '0.56'},
 'O3(ppb)': {'2018/01': '21.50',
  '2018/02': '24.80',
  '2018/03': '36',
  '2018/04': '35.90',
  '2018/05': '22.90',
  '2018/06': '24.70',
  '2018/07': '19',
  '2018/08': '19.60',
  '2018/09': '27',
  '2018/10': '43.70',
  '2018/11': '30.20',
  '2018/12': '26.40'},
 'PM10(μg/m3)': {'2018/01': '79',
  '2018/02': '72',
  '2018/03': '65',
  '2018/04': '57',
  '2018/05': '39',
  '2018/06': '39',
  '2018/07': '31',
  '2018/08': '29',
  '2018/09': '48',
  '2018/10': '71',
  '2018/11': '69',
  '2018/12': '74'},
 'NOx(ppb)': {'2018/01': '40.23',
  '2018/02': '32.38',
  '2018/03': '27.29',
  '2018/04': '20.21',
  '2018/05': '17.90',
  '2018/06': '19.93',
  '2018/07': '18.23',
  '2018/08': '22.59',
  '2018/09': '20.58',
  '2018/10': '24.65',
  '2018/11': '31.94',
  '2018/12': '35.46'},
 'NO(ppb)': {'2018/01': '8.67',
  '2018/02': '5.31',
  '2018/03': '3.54',
  '2018/04': '2.80',
  '2018/05': '4.30',
  '2018/06': '5.56',
  '2018/07': '4.85',
  '2018/08': '7.25',
  '2018/09': '4.31',
  '2018/10': '3.49',
  '2018/11': '5.64',
  '2018/12': '6.50'},
 'NO2(ppb)': {'2018/01': '31.55',
  '2018/02': '27.07',
  '2018/03': '23.75',
  '2018/04': '17.43',
  '2018/05': '13.59',
  '2018/06': '14.38',
  '2018/07': '13.39',
  '2018/08': '15.34',
  '2018/09': '16.27',
  '2018/10': '21.17',
  '2018/11': '26.30',
  '2018/12': '28.96'},
 'THC(ppm)': {'2018/01': '2.21',
  '2018/02': '2.15',
  '2018/03': '2.07',
  '2018/04': '1.98',
  '2018/05': '1.89',
  '2018/06': '1.94',
  '2018/07': '1.92',
  '2018/08': '1.97',
  '2018/09': '2.01',
  '2018/10': '2.16',
  '2018/11': '2.19',
  '2018/12': '2.21'},
 'NMHC(ppm)': {'2018/01': '0.26',
  '2018/02': '0.20',
  '2018/03': '0.16',
  '2018/04': '0.13',
  '2018/05': '0.11',
  '2018/06': '0.14',
  '2018/07': '0.13',
  '2018/08': '0.14',
  '2018/09': '0.15',
  '2018/10': '0.19',
  '2018/11': '0.23',
  '2018/12': '0.24'},
 'CH4(ppm)': {'2018/01': '1.95',
  '2018/02': '1.95',
  '2018/03': '1.91',
  '2018/04': '1.85',
  '2018/05': '1.78',
  '2018/06': '1.80',
  '2018/07': '1.79',
  '2018/08': '1.83',
  '2018/09': '1.86',
  '2018/10': '1.97',
  '2018/11': '1.96',
  '2018/12': '1.97'}}

In [7]:
pd.DataFrame(result)

,SO2(ppb),CO(ppm),O3(ppb),PM10(μg/m3),NOx(ppb),NO(ppb),NO2(ppb),THC(ppm),NMHC(ppm),CH4(ppm)
2018/01,6,0.62,21.50,79,40.23,8.67,31.55,2.21,0.26,1.95
2018/02,4.30,0.59,24.80,72,32.38,5.31,27.07,2.15,0.20,1.95
2018/03,6.30,0.45,36,65,27.29,3.54,23.75,2.07,0.16,1.91
2018/04,7.10,0.34,35.90,57,20.21,2.80,17.43,1.98,0.13,1.85
2018/05,9.40,0.23,22.90,39,17.90,4.30,13.59,1.89,0.11,1.78
2018/06,7.90,0.33,24.70,39,19.93,5.56,14.38,1.94,0.14,1.80
2018/07,6,0.27,19,31,18.23,4.85,13.39,1.92,0.13,1.79
2018/08,7.60,0.37,19.60,29,22.59,7.25,15.34,1.97,0.14,1.83
2018/09,7.10,0.35,27,48,20.58,4.31,16.27,2.01,0.15,1.86
2018/10,6.70,0.47,43.70,71,24.65,3.49,21.17,2.16,0.19,1.97
2018/11,6.40,0.52,30.20,69,31.94,5.64,26.30,2.19,0.23,1.96
2018/12,5.60,0.56,26.40,74,35.46,6.50,28.96,2.21,0.24,1.97