In [1]:
import requests
from selenium.webdriver.support.ui import Select
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np

url = 'https://taqm.epa.gov.tw/taqm/tw/MonthlyAverage.aspx'
payload = {
'ScriptManager1': 'ctl05$UpdatePanel1|ctl05$btnQuery',
'__VIEWSTATE':'xu0k6VI2GdZbBXpk5e3mY9zvjOQrb+5K0VsxuHojYuiQhKMeUt2Op5RDsR/F7fqhRW4c9Ho9ynU6Ei7eoJEBy179rZ1LLW/XyDQfePaEB7KaacsYSXIiyBZJO9RpW5QzU5EVFPiRYMPlO6At1PzigmH88XLPjxBlITfuWPN97xSrnfZ8FGTYNaN2ohvxJCvxVAkPMbEHtdssFP9eHAP9y1syXHGUdlxSvxrHqQ8o1gz+dDn9hyGEAOl0AmUo7rip9383jTl6dRHKR+AKXEoBVYbbuVhWSGrbjcj7d45Vhhtx+eS5sq3Zggqp6dQibNGuWmha5iK+c5kZKyte5L1pNJD+5Ffvq7gbGgoD+e5KllJpKUxzDzzuvAyHYaBPGttuteDnrUY/HcNzCID/ELBud40p0QlWIrAZbrEw1xZjdPMUeN43Z0L7qpjXX4sPZ44Frhoe7jEmNP9hvAq2HJpJOIoOf04HDmmCJvqJ51UolmYgZQQF465ICoDnc0uHvode1zIjMldYr7A97GsPi8Wa6lSyFr7TaFx09YJ0pKBhrBXIF6nfLhf1MPLqscVXbGmv8igQQwX5z2LfC/opUpG7CCNtJR+bUoEgH5vKy/PgBgeR7u1IVqImWalGotSudgoTqso78r6SPTXee0FBulhTzyDABDFLYj7938tMduoNnZJx+S56/o6O2RhPXHLZ/toXInpHP1K8+DUkT9pIb0iYJt6VGweZxVB51e0+g97C1ktpvXkA3zOLF1aeXzzc9L8Q8hHC6HgoztSQMVUTWX9yzRYp/3w43FD9Tk8NnhdrbRNTvnSSkEADFrsOzcrkcy1+JaTNm4nRq4t6Rs8qikx0JCSNkog6HT34aCWHNVRJSYCIrU9nrKGAvPNeYGIKgh6xCFXFxarKl/PyyCEv4zsTyuTUHYz9omZXlYnMF6tFFiX4fiuyFixCyL7jcEaqGhKfZAglhaboPzmx1DHQSxLsyHjRjwQduFFJD+HVfssy9m7w7LybixFugQFef/yMnzhNrdyt85R63TzJhzMRYGX7cptlgfqSHdWa7ertFBURyjBMfokOexC5eZtWlxVUc9R4IlpEypVTZYeugxQAOESoaEfkyOCj9mwVGhh67SepN/upHdiOXfHi+Y6UNeez4a/gqx/Ysh9qK+6N3B0DojvxN2ViQee7PwcIMPw+ZM1ErU7/IDA2CMAkMPnOrOPrR8iGcxiXVVMb8Va+qjydBuA02ZwpNoFQVo4TK8oyyqe+P7XPGPjRQm4xMxi+FwTcv3w9KvInXd8QetHUwB8kL745v83GNwEaXE6RBQ4sqCoKGu2a1yK3xm7lY8o1V+uUqsEY+LWsGnBFE8uQjjKrWejRKk2JdsY06MkvHf5PpWTpaedb9cwCUH0WRAOBywxRQNTbl6QrGzCGp3/g1JUfoRX0/IaXhBAK+PPawsulndi/mFEmUUcWyQB73AD/AaNWSNvLnryE3qYcg9vN+uemZKtpWAaCRRr7OIcSgwJosr9PPLyrv3uDVMbYmfUMnf3rDxAvHuHg5bhaoLTGKzLBPNkFcXijwuXzfV0JcOM+9ndmgceF6/lQuQgA7sSzf9QNlefcuZR/50WZWhUofl4i6sqgdRPqneeFNnO6Nk2U00DqX/PQX92PJI1jPI0PLZPyrZJBtIVvibIhQ8VT6XJ39CCabwjrVdH8I+l0ImHhZd3mazX6j7bZPm6DGWnrfshiux7xi64wp/0D6nD1Kebt4i8V4n9GdhbDv5xkFhnD5q6p7ibVbfEd7d99iKpwaMC58RH5RM4DdE8wiqNbrcvnlXgZc3pml15B5GPmnDLLpcEILcKjJCoi7RSbhOwrIHeMNz3cl42wOY75GBXGiD/jkZlVd1b6RFgGiJJ58T9H62MgLwEFOOLkCJDTanUaXhPhLuO9D9xK3oIf6QZNPviiPO+tcHLz+Wdvm+mTcH2Ow5KYATcTRcYo+b+dQ0Va/cJ2nSlmpLOgD0jl8niA8GQUN3nBSegpAWPbFiSLbYr516OGMhYVeK7pRQGakZ4nLsQCTp18T72DiDqg0RAwc9jwt1lj+xlcmvHO0aqhFOIA+BWCss5LyZu8BIlveU/KiZngjBTqJ86tVsgncaUcwx2LiwE8DIz6ePZYXknrbxftXk+BzEEXiGyZ8r7cUBIrpzxfvYjjuVHHLOWU9lmMQH2MPQeG5yxPXtOaX25tSZgMtv51MtIdbcZAAwwLUQ3nkFOD61/z38JKwlkXRISFM8/mAOOmyYneKN5jpdjFxI03t622jv0iJDbTgg7Bi0RACZ9d8PEf1H79yFA74pkLvh5dVZIjeaKxX7RMj1cJtgMbYbxdBgYmTl1fREl3EIlxFRJKmLLd88Di2UDjb+yBJwzsveaqad1f94Ucvt5yWX0hHc4B3pfMkaXw5yLnFSAVYZHBvFBL4Oy0W3YlHam48XVYWXgnpEyvgtKQHHpN085zKzHMCi3j5nQsP16QtQvlUwshYjqeTLdseLtzjo3ro9CMgMi5gkBflJ5y3qiyC0nAKQ9MDGnInmeS4iHjL/KRHI/Ta2oaOYMhiVbfaj41qfHuLNGMQY3g0y8+eHe7UM/K3xFxW+SfONdLGOeoyKBpfgD73DsNQ3cTDQ1q8py4s7VUdyyUskJU/fht8yx5TaJZ8DAePANzvwdbLBuminkv7zFT8sn0QVfWbi2Zp3fxG/DPuJFWmOqEo7ySreIKeFvDtlC38kX+/J0dDdIAca2ZSQ5Nbuh9lB/ApxAPl3KOCxcCeutwWHDHHHroR9tcEx2uPkR9Ji6kzw05E7pNPV/RTV8DHUpIEDWQcH0dhQxCiBnOdOFMvSCHHwGwiyXBBnvOJTV84EbnxGza3+WG85Wl8uc7ZVAoNMbkxF18D18cfZzUX8SXAK5nfcWchlApdO6Zwc5eilsMEc+0nQneWqjZMPDScVKsNskcUC+ATaO3VptFD0auJVhhbjfdqK+tNONMkQ+aWhsbaRIjGsPiEb2jPw6qOpjOdOM+3LOQGMVMkR5iQNM9lcmeKoBbi+Gn74WHSOBpK7p2Gu/yJSIqIGPLALA52JSCfqJXDPiClDBlB6CQOH2gBB+ISVqNs9Oa/UsmBku7MKerr3fANSBwxWbiKsYxDYqsptcCvA==',
'__VIEWSTATEGENERATOR': '0C858E1A',
'__EVENTVALIDATION':'6pSM/OxHRC5Qnm7P6AOxBriGRRbqi0rJg5yjBLQR44Cucl0vwThHfGBfB7os/8t5xTJK2WcWInAuxI+kV0ofdYNF11cmsGRzbkQEd5dQtBNSdKTzQYxH5OITnpIh1pfKovT9wpE70RIJCsd9YuaCZ2Bvj3mZOKvXhtzj77ArTreGRy7E+CUW4/DSB8gA3Qx4iy0bNs/VMMrGOe19ttn5sV58XT7MVV/ATnREmzYu4bkRMWHk+6jkShTgnOMd+44G7pYxdZ6vXL2zjvAo885+kCF+Sh2iDUpmU6BsBIp2DsWi1ROZznAuFJKf5OE0n4lS58io8iyBEJ8ZU/Ovo7q4r7wra93Cdh9xYEjboOdR+EHAm8aDaBIr1fWqADG1SqiS91AcmrW1ygRI/YoHnfqhtjp7GR4FKcWdePKsurtRWXRe8AdKyfXlFMc4Ff7zkD2lFGh+2dCrPsdF+lkk0TOZ5uXy1H0My5GHdO1fYpjC7MHkJ22nU4yT8iWRuk2fwPZ8G5MvlYWSYiY1RjCWb0e2WObxTJZp6EtPma+0lY1+5JPN498MFTxsDOfEjX4EARm/979qhHMaCsTg2I/WPJGBexOXOYeuUgzhgjcXTZaH+jSO4xbbvMq2iRbwFk9ES21ToyzWrLwhZeB0NnVxLYxCeKPDbWEd7W784DjMXux8BOCySreh69sYT1qKHht7eh6+0/K1z2HEkVRH4roGwUOD7ZtYn71uYyq62lswMQy3NYeTsqKKCw8A+terbpy5E5oJYLAUIqG8ImeVyG7rw28eunh28Srfl7oaaTgtQGFXwgX2gjLXB5vmlryQVgc+kyjF+Ahusyxea9qhpeIzp1AZAU1pS+n/xGEPhYoQU2KqSRIzqdV8XQC1/H7IiKFLG50ZbZpi6qXOa7cK5TmiBsPaH9hIHElPc5+/MD8ffJP9fCdGhTu1Gs94Eev7aWWElZC/VIBzofvz6NBz7jip/aEqBgHYJFo=',
'ctl05$ddlSite': '11',
'ctl05$ddlYear': '2019',
'ctl05$btnQuery': '查詢',
}
r = requests.post(url, data=payload)
r.status_code

200

In [2]:
soup = BeautifulSoup(r.text, 'html.parser')
table = soup.find('table', class_='TABLE_G')
print(table)

<table align="Center" border="1" cellpadding="3" cellspacing="0" class="TABLE_G" id="ctl05_gv" rules="all" style="border-color:Black;border-width:1px;border-style:None;border-collapse:collapse;">
<tr style="color:Black;font-weight:normal;">
<th scope="col">監測項目</th><th scope="col">單位</th><th scope="col">監測日期</th><th scope="col">監測值</th><th scope="col">標註</th>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">SO2</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2019/01</td><td>1.80</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/02</td><td>1.60</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/03</td><td>1.90</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/04</td><td>2.20</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/05</td><td>1.70</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/06</td><td>1.90</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/07</td><td>2.10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/08</td><td>2</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/09</td><td>2</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/10</td><td>1.90</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/11</td><td>1.80</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/12</td><td>1.90</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">CO</td><td class="no-alt" rowspan="12" valign="top">ppm</td><td>2019/01</td><td>0.40</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/02</td><td>0.43</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/03</td><td>0.40</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/04</td><td>0.41</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/05</td><td>0.32</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/06</td><td>0.35</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/07</td><td>0.28</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/08</td><td>0.21</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/09</td><td>0.25</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/10</td><td>0.28</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/11</td><td>0.25</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/12</td><td>0.37</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">O3</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2019/01</td><td>35</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/02</td><td>33.40</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/03</td><td>45.50</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/04</td><td>41.70</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/05</td><td>42.40</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/06</td><td>27.30</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/07</td><td>23.80</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/08</td><td>24.70</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/09</td><td>28.70</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/10</td><td>46.40</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/11</td><td>42.80</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/12</td><td>32.10</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">PM10</td><td class="no-alt" rowspan="12" valign="top">μg/m3</td><td>2019/01</td><td>28</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/02</td><td>29</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/03</td><td>37</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/04</td><td>36</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/05</td><td>32</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/06</td><td>25</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/07</td><td>22</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/08</td><td>17</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/09</td><td>18</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/10</td><td>29</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/11</td><td>26</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/12</td><td>21</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NOx</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2019/01</td><td>14.95</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/02</td><td>15.39</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/03</td><td>15.43</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/04</td><td>16.25</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/05</td><td>13.75</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/06</td><td>17.71</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/07</td><td>13.93</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/08</td><td>10.05</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/09</td><td>11.12</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/10</td><td>10.04</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/11</td><td>9.61</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/12</td><td>17.06</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NO</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2019/01</td><td>3.54</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/02</td><td>2.76</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/03</td><td>2.74</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/04</td><td>2.82</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/05</td><td>2.45</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/06</td><td>3.91</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/07</td><td>2.87</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/08</td><td>2.33</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/09</td><td>2.66</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/10</td><td>2.17</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/11</td><td>2.22</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/12</td><td>4.77</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NO2</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2019/01</td><td>11.42</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/02</td><td>12.63</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/03</td><td>12.69</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/04</td><td>13.43</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/05</td><td>11.30</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/06</td><td>13.81</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/07</td><td>11.06</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/08</td><td>7.73</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/09</td><td>8.46</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/10</td><td>7.88</td><td> </td>
</tr><tr style="color:Black;">
<td>2019/11</td><td>7.39</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2019/12</td><td>12.29</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="1" style="white-space:nowrap;" valign="top">THC</td><td class="no-alt" rowspan="1" valign="top">ppm</td><td> </td><td> </td><td>無此測項</td>
</tr><tr class="ALT" style="color:Black;">
<td class="no-alt" rowspan="1" style="white-space:nowrap;" valign="top">NMHC</td><td class="no-alt" rowspan="1" valign="top">ppm</td><td> </td><td> </td><td>無此測項</td>
</tr><tr style="color:Black;">
<td style="white-space:nowrap;">CH4</td><td>ppm</td><td> </td><td> </td><td>無此測項</td>
</tr>
</table>

In [3]:
dataList = []
c = 0
tList = []
for i in table.find_all('td'):
    tList.append(i.text.replace('\n','').replace('\xa0',''))
    c += 1
    while c==38:
        dataList.append(tList)
        tList = []
        c = 0
        
result = {}
for i in dataList:
    title = '{}({})'.format(i[0], i[1])
    c = 0
    tList = []
    rList = {}
    for data in i[2:]:
        tList.append(data)
        c += 1
        while c%3 == 0:
            rList[tList[0]] = tList[1]
            c = 0
            tList = []
            break
    result[title] = rList
pd.DataFrame(result)

        SO2(ppb) CO(ppm) O3(ppb) PM10(μg/m3) NOx(ppb) NO(ppb) NO2(ppb)
2019/01     1.80    0.40      35          28    14.95    3.54    11.42
2019/02     1.60    0.43   33.40          29    15.39    2.76    12.63
2019/03     1.90    0.40   45.50          37    15.43    2.74    12.69
2019/04     2.20    0.41   41.70          36    16.25    2.82    13.43
2019/05     1.70    0.32   42.40          32    13.75    2.45    11.30
2019/06     1.90    0.35   27.30          25    17.71    3.91    13.81
2019/07     2.10    0.28   23.80          22    13.93    2.87    11.06
2019/08        2    0.21   24.70          17    10.05    2.33     7.73
2019/09        2    0.25   28.70          18    11.12    2.66     8.46
2019/10     1.90    0.28   46.40          29    10.04    2.17     7.88
2019/11     1.80    0.25   42.80          26     9.61    2.22     7.39
2019/12     1.90    0.37   32.10          21    17.06    4.77    12.29